FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  breakoutroomactivity.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/breakoutroomactivity.py
FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  breakoutroomactivity.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/breakoutroomactivity.py
FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  breakoutroomactivity.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/breakoutroomactivity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  breakoutroomactivity.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/breakoutroomactivity.py
